language: generic

# We don't actually use the Travis Python, but this keeps it organized.
# The test matrix really uses the latest Miniconda for Py2 or Py3,
# and we're "fooling" Travis into doing this for us.
matrix:
    include:
    - os: linux
      dist: trusty
      env: TOXENV=2
    - os: linux
      dist: trusty
      env: TOXENV=3
    - os: osx 
      osx_image: xcode8
      env: TOXENV=3
    - os: osx
      osx_image: xcode7.2
      env: TOXENV=3
    - os: osx 
      osx_image: xcode8
      env: TOXENV=2
    - os: osx
      osx_image: xcode7.2
      env: TOXENV=2

sudo: true

notifications:
    email: false

install: 
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$TOXENV" == "2" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi; fi;
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$TOXENV" == "3" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TOXENV" == "2" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TOXENV" == "3" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda install gcc
    # Need GSL 1.16, which is the "bioconda-approved" version
    - conda install -c r gsl
    - conda install -c bioconda libsequence fwdpp
    - conda install pandas numpy Cython
    - conda install -c conda-forge cythongsl=0.2.1
script:
    - export LD_LIBRARY_PATH=$HOME/miniconda/lib
    - export CPPFLAGS="-I$HOME/miniconda/include $CPPFLAGS"
    - export LDFLAGS="-L$HOME/miniconda/lib $LDFLAGS"
    #- pip install --upgrade Cython  cythongsl
    #We must force OS X to use GCC.
    - CC=gcc CXX=g++ python setup.py build_ext -i --use-cython --qtrait
    - python -m unittest discover fwdpy/tests
